name = input("What's your name? ")
age = int(input("How old are you? "))
city = input("Where do you live? ")
word = input("Your favorite word: ")
num1 = int(input("Your favorite number: "))
num2 = int(input("Enter your second number: "))

sum_result = num1 + num2
subtraction = num1 - num2
multiplication = num1 * num2
division = num1 / num2
power = num1 ** num2
square_root1 = num1 ** 0.5
square_root2 = num2 ** 0.5

print()
print("===== PERSONAL INFO =====")
print()
print("Name = ", name)
print("City = ", city)
print("Aga = ", age)
print("Next year you will be ", age + 1)
print()
print("===== NAME ANALYSIS =====")
print()
print("Number of letters: ", len(name))
print("First letter: ", name[0])
print("Last letter: ", name[-1])
print("Second letter: ", name[1])
print("One to the last: ", name[-2])
print("Lowercase letters: ", name.lower())
print("The place of the first letter 'a': ", name.find("a"))
print()
print("===== WORD ANALYSIS =====")
print()
print("Number of letters: ", len(word))
print("First letter: ", word[0])
print("Last letter: ", word[-1])
print("Second letter: ", word[1])
print("One to the last: ", word[-2])
print("Lowercase letters: ", word.lower())
print("The place of the first letter 'e': ", word.find("e"))
print()
print("===== NUMBER ANALYSIS =====")
print()
print("Sum_result: ", sum_result)
print("Sutraction: ", subtraction)
print("Multiplication: ", multiplication)
print("Division: ", division)
print("Power of the first number to the second: ", power)
print("Square root number1: ", square_root1)
print("Square root number2: ", square_root2)
print()
print("===== DATA TYPES =====")
print()
print("Name data type: ", type(name))
print("Age data type: ", type(age))
print("Favorite Word data type: ", type(word))
print("Favorite Number data type", type(num1))