name = input("What's your name? ")
age = int(input("How old are you? "))
city = input("Where do you live? ")
num = int(input("Your favorite number: "))

print("Hello ", name)
print("your city is ", city)
print("You will be ", age + 1 ,"years old next year.")
print("Number of letters: ", len(name))
print("First letter: ", name[0])
print("Last letter: ", name[-1])
print("Lowercase version: ", name.lower())
print("The place of the first letter 'a': ", name.find("a"))
print("Square number: ", num ** 2)
print("Square root number: ", num ** 0.5)