name = input("What's your name? ")
age = int(input("How old are you? "))
city = input("Where do you live? ")
num1 = int(input("Enter number_1: "))
num2 = int(input("Enter number_2: "))
word = input("Enter your word: ")
print()
print("===Personal info===")
print("Hi ", name)
print("your city is ", city)
print("You will be ", age + 1 ,"years old next year.")
print()
print("===Name info===")
print("Number of letters: ", len(name))
print("First letter: ", name[0])
print("Last letter: ", name[-1])
print("Lowercase version: ", name.lower())
print()
print("===Word info===")
print("Number of letters: ", len(word))
print("First letter: ", word[0])
print("Last letter: ", word[-1])
print("The place of the first letter 'a': ", word.find("a"))
print()
print("===Math info===")
print("Sum: ", num1 + num2)
print("Subtraction: ", num1 - num2)
print("Multiplication: ", num1 * num2)
print("Division: ", num1 / num2)
print("power: ", num1 ** num2)
print("Square root first number: ", num1 ** 0.5)
print("Square root second number: ", num2 ** 0.5)